language: c

env:
  global:
    - RTRAVISPATH=$HOME/r-travis
    - RTRAVISR="" # add custom R code to be executed before installing package
  matrix:
    - RTRAVISTYPE=quick
    - RTRAVISTYPE=full

# install dependencies
install:
  - curl -L https://raw.github.com/krlmlr/R-travis/master/r-travis -o $RTRAVISPATH
  - chmod +x $RTRAVISPATH
  - sudo -E $RTRAVISPATH/r-travis install

# run tests
script:
  - $RTRAVISPATH/r-travis test
