language: c

env:
  global:
    - RTRAVISPATH=$HOME/r-travis
    - RTRAVISR="install_github(c('assertthat', 'testthat'));"
  matrix:
    - RTRAVISTYPE=quick
    - RTRAVISTYPE=full

# install dependencies
install:
  - cp r-travis $RTRAVISPATH
  - sudo -E $RTRAVISPATH install

# run tests
script:
  - "cd fakepackage && $RTRAVISPATH test"
