#!/bin/sh

set -e

# Add RStudio's CRAN repository
echo -e "deb http://cran.rstudio.com/bin/linux/ubuntu precise/\ndeb-src http://cran.rstudio.com/bin/linux/ubuntu precise/" | sudo dd status=noxfer of=/etc/apt/sources.list.d/cran.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cran.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

# Add Michael Rutter's c2d4u repository
sudo apt-add-repository -y ppa:marutter/c2d4u
sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-c2d4u-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

# Install recommended R packages, and LaTeX
sudo apt-get install --no-install-recommends r-base-dev r-cran-xml r-cran-rcurl r-recommended qpdf texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra

# Install crant
git clone https://github.com/krlmlr/crant.git ~/crant

