#!/bin/sh

set -e
set -v

install() {
    # Allow other user access to root's home
    chmod go+rx ~root

    # Add RStudio's CRAN repository
    echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/\ndeb-src http://cran.rstudio.com/bin/linux/ubuntu precise/" > /etc/apt/sources.list.d/cran.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/cran.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

    # Add Michael Rutter's c2d4u repository
    apt-add-repository -y ppa:marutter/c2d4u
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-c2d4u-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

    echo "RTRAVISTYPE: $RTRAVISTYPE" >> /dev/stderr
    case "$RTRAVISTYPE" in
        quick) true;;
        full | "") extra_packages="qpdf texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra"; true;;
        *) echo "Unsupported RTRAVISTYPE." >> /dev/stderr; false;;
    esac || exit 1

    # Install recommended R packages, and LaTeX
    apt-get install --no-install-recommends r-base-dev r-cran-xml r-cran-rcurl r-recommended $extra_packages

    # Install crant, accessible for everyone
    git clone https://github.com/krlmlr/crant.git ~root/crant
}

test() {
    mode="$1"
    shift

    case "$mode" in
        stable | devel) true;;
        "") echo "No mode specified." >> /dev/stderr; false;;
        *) echo "Unsupported mode $mode." >> /dev/stderr; false;;
    esac || exit 1

    echo "Checking against R-$mode version." >> /dev/stderr

    export R_LIBS_USER=$HOME/R-$mode

    if [ $mode = "devel" ]
    then
        sudo add-apt-repository -y ppa:marutter/rdev
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-rdev-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
        sudo apt-get dist-upgrade
    fi

    rm -rf $R_LIBS_USER
    mkdir $R_LIBS_USER

    R --version
    R -e '.libPaths(); sessionInfo()'
    R --vanilla --slave -e 'install.packages(c("devtools"), repos=c("http://cran.rstudio.com"))'
    R --vanilla --slave -e 'library(devtools); install_github("devtools")'
    R --vanilla --slave -e 'options(repos = c("http://rforge.net", "http://cran.rstudio.org")); library(devtools); devtools:::install_deps(dependencies = TRUE); '"$RTRAVISR"' install()'
    ~root/crant/rant -S -r
}

command="$1"
shift

case "$command" in
    install | test) $command "$*";;
    *) echo "Unsupported command $command." >> /dev/stderr; false;;
esac
